language: node_js
sudo: false
node_js:
  - v0.10
  - v4

cache:
  directories:
    - node_modules

before_install:
  - npm install -g npm@3
install:
  - npm install

script:
  - if [[ $TRAVIS_NODE_VERSION == "v0.10" ]]; then npm run test-es5; fi;
  - if [[ $TRAVIS_NODE_VERSION != "v0.10" ]]; then npm run test; fi;
after_success:
  - npm run coveralls
  - npm run semantic-release
