language: node_js
sudo: false
node_js:
  - 4
  - 6
  - 8
  - 9

before_install:
  - curl -L https://unpkg.com/@pnpm/self-installer | node
install:
  - pnpm install

after_success:
  - npm run coveralls

notifications:
  email:
    on_success: never
    on_failure: never
